### ISSUE TITLE
PredictProbabilities values

### ISSUE THREAD

**Issue by Lucy83** [nicolaspanel/libsvm.net#17]
This call:

var probabilities = svm.PredictProbabilities(x);

always returns 0 to all classes. What can be the cause of this?

**Comment by nicolaspanel** [comment]
It is hard to say without more information.

Could you  tell us more about: 
 - your dataset (size, number of classes, etc.)
 - parameters used to initialize the SVM

**Comment by Lucy83** [comment]
Hi,

learning samples:
I used 2 classes, each having about 100 attributes (2 values for each attribute)

When I discovered that predicted probabilities were 0 every time I teached SVM, I decided to extend learning samples. Still using 2 classes, I generated 10000 attributes (2 random vlaues for each attribute).

This is how I initialize SVM core:
this.svcEngine = new C_SVC(this.LearningProblem, KernelHelper.LinearKernel(), 1);

**Comment by nicolaspanel** [comment]
it is likely that the problem comes from your dataset.  

PS: you should also take a look to [this guide](http://www.csie.ntu.edu.tw/~cjlin/papers/guide/guide.pdf)?

**Comment by Lucy83** [comment]
Yes I've read guide you pointed me at.

I wrapped your API with a lot of classes, but here I present the 'simple' version of how I am preparing data for SVM learning:

```
        public static svm_problem CreateLearningProblemTest()
        {
            List<List<double>> inputData = new List<List<double>>();
            Random rnd = new Random();

            for (int i = 0; i < 5000; i++)
            {
                List<double> inputDataItem = new List<double>();

                double classValue = 1;
                int x = rnd.Next(0, 100);
                int y = rnd.Next(80, 200);

                inputDataItem.Add(classValue);
                inputDataItem.Add(x);
                inputDataItem.Add(y);

                inputData.Add(inputDataItem);
            }

            for (int i = 0; i < 5000; i++)
            {
                List<double> inputDataItem = new List<double>();

                double classValue = 0;
                int x = rnd.Next(0, 100);
                int y = rnd.Next(0, 100);

                inputDataItem.Add(classValue);
                inputDataItem.Add(x);
                inputDataItem.Add(y);

                inputData.Add(inputDataItem);
            }

            //return ProblemHelper.ReadAndScaleProblem(inputData);
            return ProblemHelper.ReadProblem(inputData);
        }
```

I still can't think of, what possibly can be wrong with my data set.
Predicted Class value seems to be good (when tested for smaller and ordered dataset), but I can't get any probability results.

**Comment by nicolaspanel** [comment]
To predict probabilities you have to enable it 

try this: 
```c#
this.svcEngine = new C_SVC(this.LearningProblem, KernelHelper.LinearKernel(), 1, 100, true);
```

See also : 
 - https://www.csie.ntu.edu.tw/~cjlin/libsvm/faq.html#/Q06:_Probability_outputs
 - https://github.com/nicolaspanel/libsvm.net/blob/master/LIBSVM/SVC/C_SVC.cs#L14

**Comment by Lucy83** [comment]
Thanks, setting true flag worked like a charm :)
