### ISSUE TITLE
Hello can you please update dll file to latest 3.2?

### ISSUE THREAD

**Issue by MonsterMMORPG** [nicolaspanel/libsvm.net#18]
Hello can you please update dll file to latest 3.2?

I replaced your dll file however it is not working

Also please make sure it works even with x64 application ty

**Comment by nicolaspanel** [comment]
Did you have bugs with the current version (3.17)? If so, could you include the stacktrace?

**Comment by MonsterMMORPG** [comment]
your latest version says 2.1.8 here : https://github.com/nicolaspanel/libsvm.net

anyway i solved my problem with making libsvmsharp working in 64 bit :)

ty for answer

**Comment by nicolaspanel** [comment]
2.1.8 is libsvm.net version. libsvm version is 3.17, see https://github.com/nicolaspanel/libsvm.net#how-it-works
