### ISSUE TITLE
File format

### ISSUE THREAD

**Issue by oktaysoftwarer** [nicolaspanel/libsvm.net#19]
Hello Nicolas,
In the below code what are the "TRAINING_FILE" and "TEST_FILE" formats?Are those txt files?

var prob = ProblemHelper.ReadAndScaleProblem(TRAINING_FILE);
var test = ProblemHelper.ReadAndScaleProblem(TEST_FILE);

var svm = new C_SVC(prob, KernelHelper.RadialBasisFunctionKernel(gamma), C);
var accuracy = svm.GetCrossValidationAccuracy(nr_fold);// with nr_fold > 1
for (int i = 0 ; i < test.l ; i++)
{
    var x = test.x[i];
    var y = test.y[i];
    var predictedY = svm.Predict(x); // returns the predicted value for 'x' attributes
    var probabilities = svm.PredictProbabilities(x);  // returns the probabilities for each class
    // Note : in about accuracy% of cases, 'predictedY' should be equal to 'y'
}

**Comment by nicolaspanel** [comment]
Yes, they are text file using [libsvm](https://www.csie.ntu.edu.tw/~cjlin/libsvm/) format
