### ISSUE TITLE
one-class SVM

### ISSUE THREAD

**Issue by shahabe** [nicolaspanel/libsvm.net#22]
Hi, 
I want to learn one-class SVM but I think it is not implemented in this version.
Can you help me implement? Or if there is anything useful please advice.
Thanks.

**Comment by nicolaspanel** [comment]
Hi,

The best way to do that is:
1. fork this repo
2. Make sure you understand what one-class SVM are (see [this](http://scikit-learn.org/stable/modules/svm.html#svm-outlier-detection) for more info)
3. take a look at the current implementation to see how it uses libsvm library, especially the [SVM abstract class](https://github.com/nicolaspanel/libsvm.net/blob/master/LIBSVM/SVM.cs#L24). 

Note: Required parameters for one-class SVM are:
 - `svm_type`: always equal to `2` 
 - `nu`: default value is `0.5` 
 - `kernel_type`: integer , see [this](https://github.com/nicolaspanel/libsvm.net/blob/master/LIBSVM/KernelType.cs)
 -  Other parameters depending on what kernel you use:
   - LINEAR: No parameter
   - POLY: degree (`default=3.`), gamma (`default=1/num_features`), r (`default=0.`)
   - RBF: gamma (`default=1/num_features`)
   - SIGMOID: gamma (`default=1/num_features`), r (`default=0.`)
see [this](https://www.csie.ntu.edu.tw/~cjlin/libsvm/#gui) for more info

BTW, if you are just interested in one-class SVM, maybe you should build your own solution on top of the libsvm dll ( [lib/libsvm.dll](https://github.com/nicolaspanel/libsvm.net/tree/master/lib))
