### ISSUE TITLE
Alternative serialization

### ISSUE THREAD

**Issue by ChristosManosEmpora** [nicolaspanel/libsvm.net#23]
Could it be possible to provide an alternative way for serialization/desierialization?

Specifically, I would be interested on being able to save the "svm_model model" my way. Could you please provide methods that return a stream at saving and require that stream (instead of a file name) for loading the model?

**Comment by nicolaspanel** [comment]
sorry but I can't implement this kind of features right now.
If you finally manage to do this by yourself, I'd be pleased to merge it ;)
BR

**Comment by ChristosManosEmpora** [comment]
Hey, thank you for the fast reply. I will do it. Could you please help me
with the github? What do i have to do to start working on it?

Thanks,

Christos

**Comment by nicolaspanel** [comment]
all you have to do is to fork the project (see  [this tutorial](https://help.github.com/articles/fork-a-repo/) for more info)

**Comment by ChristosManosEmpora** [comment]
Hello Nicolas,

   Thanks for the help.
I have prepared the new branch under my (personal) "celetron" account:
I am also including a testing method in the C_SVC_Tests.cs fiile.
Could you please take a look on it and if everything is alright merge?

Many thanks

Christos Manos
